language: node_js
node_js:
  - "12"
  - "13"

env:
  - NODE_ENV=TEST

addons:
  chrome: stable

install:
  - npm run install:all

script:
  - npm test

cache:
  directories:
    - ./node_modules
    - ./client/node_modules
    - ./server/node_modules
